version: '2'
services:
  glassfish:
    build: ../images/glassfish
    links:
     - mysql:db
    ports:
     - "8080:8080"
     - "4848:4848"
  wildfly:
    build: ../images/wildfly
    links:
     - mysql:db
    ports:
     - "9090:8080"
     - "9990:9990"
  tomcat:
    build: ../images/tomcat
    ports:
     - "7070:8080"
  mysql:
    build: ../images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db